Survey One review
rust-embedded/wg pull request #787
Opened 2024-08-13 18:07 UTC by jamesmunns

CC #782 

This follows the [requested format](https://github.com/rust-lang/surveys/blob/main/surveys/notes/reference.md) for submission.

Once we have reviewed and merged this PR, I will copy the survey "upstream" to submit it to the survey team.

2024-08-13 18:14 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- nRF52 (Nordic Semiconductor)
```suggestion
- nRF (Nordic Semiconductor)
```

Nordic has many more families now, including nRF52, 53, 54, and 91, so let's just go for "nRF"

2024-08-13 18:15 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- defmt
```suggestion
- cross
- defmt
```

2024-08-13 18:18 UTC, jamessizeland commented
Best to have an option under using embedded rust at work for shipping none, could be for internal use only, evaluation, future intention, etc.

2024-08-13 18:20 UTC, jamesmunns commented
> Best to have an option under using embedded rust at work for shipping none, could be for internal use only, evaluation, future intention, etc.

Added in 11e66a1

2024-08-13 18:24 UTC, jannic commented on surveys/2024-08-survey.md
> +- More than 10000 devices per year
Which choice should be selected by a company currently developing, but not yet shipping, a device using rust?

2024-08-13 18:26 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- More than 10000 devices per year
I would probably say the `Zero devices (only internal or non-production usage)` option, the goal here is to gauge "in the field" numbers, IMO!

2024-08-13 18:28 UTC, jamessizeland commented on surveys/2024-08-survey.md
> +### What frameworks or RTOSs are you using with embedded Rust?
Worth an explicit mention of Zephyr?

2024-08-13 18:28 UTC, jamessizeland commented on surveys/2024-08-survey.md
> +- probe-rs
espflash?

2024-08-13 18:31 UTC, Vollbrecht commented on surveys/2024-08-survey.md
> +### What chip families are you using embedded Rust with?
```suggestion
### What chip families do you use or plan to use with embedded Rust?
```
That way people interested but not using Rust would potentially not skip the question. Though that would change who we track here, so its debatable if that should be included or not.

2024-08-13 18:31 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +### What frameworks or RTOSs are you using with embedded Rust?
Hmm, that's a good point, maybe mention "other C or C++ based RTOSs, such as Zephyr, FreeRTOS, mbed", though that might be possible for people to just write in for "Other"?

2024-08-13 18:32 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +### What chip families are you using embedded Rust with?
Open to it, i'll see if others have feedback for or against before merging!

2024-08-13 18:33 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- probe-rs
Added in 1449588

2024-08-13 18:35 UTC, Vollbrecht commented on surveys/2024-08-survey.md
> +### What architectures are you using embedded Rust with?
open to the same question as in the suggestion down below, if we should include a "plan to use"  into the question.

2024-08-13 19:12 UTC, jamessizeland commented on surveys/2024-08-survey.md
> +### What chip families are you using embedded Rust with?
Best to time box it, "or plan to use in the next 12months"

2024-08-13 20:23 UTC, CodingInGreen commented
These questions look great! I had a question, on this survey question.

**If using for work, how many devices/year is your company shipping currently using Rust?**

Do we want to call out "embedded devices" rather than "devices", or does that matter? 

I could just be overthinking this.

2024-08-15 01:27 UTC, alistair23 requested changes

2024-08-15 01:27 UTC, alistair23 commented on surveys/2024-08-survey.md
> +- Other (open response)
What about including [bindgen](https://github.com/rust-lang/rust-bindgen) here?

It's really useful if interacting with existing C code

2024-08-15 01:27 UTC, alistair23 commented on surveys/2024-08-survey.md
> +- Exclusively C for firmware
What about a C++ option as well? I know it's similar, but it would be interesting to compare the two

2024-08-15 01:27 UTC, alistair23 commented on surveys/2024-08-survey.md
> +- Other (open response)
Any chance of adding an [Ambiq](https://ambiq.com/) option? It's one of the best supported SoCs in Tock so it would be interesting to list

2024-08-15 01:27 UTC, alistair23 commented on surveys/2024-08-survey.md
> +- School projects
School or university?

2024-08-16 13:18 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- Other (open response)
Added `bindgen` and `cbindgen`

2024-08-16 13:18 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- Exclusively C for firmware
I will rewrite these to not be specific to C, this was an oversight!

2024-08-16 13:21 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- Other (open response)
Added! I hadn't seen it used much personally, but if it is popular in Tock happy to add it!

2024-08-16 13:21 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- School projects
Updated to "School or University"

2024-08-16 13:23 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +### What chip families are you using embedded Rust with?
Decided to go with this!

2024-08-16 13:31 UTC, jamesmunns commented
Addressed all review comments so far!

2024-08-16 13:37 UTC, jamesmunns commented
Regarding timeline, I would propose:

* Aug 20th, we approve and merge this PR
* Aug 20th, I open a PR to the [surveys repo](https://github.com/rust-lang/surveys) to formally request the survey with the contents from this PR - I'll ask that we open this survey for **two calendar weeks**, to allow us enough time to coordinate the PR for this.
    * This should allow us to mention this during two WG meetings
    * This also allows us to appear in an Embedded Rustacean newsletter (next issue Aug 30th)
* Aug 22nd (approximately) we "go live"
* Sep 05th (approximately) we close responses
* Some point shortly afterwards, the embedded WG will receive the responses
* Some point after that, we should post a blog post detailing this, potentially on the "Inside Rust" blog

2024-08-17 07:45 UTC, Kobzol reviewed
Looks good overall. Left one suggestion.

2024-08-17 07:45 UTC, Kobzol commented on surveys/2024-08-survey.md
> +### What are the most common crates or libraries you use in your embedded projects?
Do you perhaps want to enumerate a few popular choices (e.g. postcard :) ) here? If there is a predetermined list, it usually gets more answers than if there is just an open text field, people are lazy to type, unsure how to separate multiple responses etc. Not to mention that it's much easier to analyze.

2024-08-17 07:45 UTC, Kobzol commented on surveys/2024-08-survey.md
> +### What are your biggest complaints or blockers for using Rust in your embedded projects?
Same here.

2024-08-19 00:03 UTC, alistair23 commented on surveys/2024-08-survey.md
> +- Exclusively other languages (C/C++/Ada/Zig) for firmware
Is it worth adding a question after this to get an idea of what languages (C/C++/Ada/Zig) people are using with Rust? It might help guide future projects

2024-08-19 00:14 UTC, jamessizeland approved these changes

2024-08-19 08:38 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- Exclusively other languages (C/C++/Ada/Zig) for firmware
I'm a little hesitant to add more questions, but I'll discuss it tomorrow in the next meeting where we wrap up the review for this!

2024-08-19 08:40 UTC, jamesmunns commented
Outstanding questions to discuss in the meeting:

* [ ] Do we want to enumerate "popular crates" to seed the list? (see [this comment](https://github.com/rust-embedded/wg/pull/787#discussion_r1720718252) )
* [ ] Do we want to enumerate "common blockers" to seed the list? (see [this comment](https://github.com/rust-embedded/wg/pull/787#discussion_r1720718866) )
* [ ] Do we want to add a question asking what other languages are used in embedded Rust projects? (see [this comment](https://github.com/rust-embedded/wg/pull/787#discussion_r1721093403) )

2024-08-20 18:39 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +- Exclusively other languages (C/C++/Ada/Zig) for firmware
Added!

2024-08-20 18:40 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +### What are your biggest complaints or blockers for using Rust in your embedded projects?
Decided against! We will reconsider in future surveys

2024-08-20 18:40 UTC, jamesmunns commented on surveys/2024-08-survey.md
> +### What are the most common crates or libraries you use in your embedded projects?
Decided against! We will reconsider in future surveys

2024-08-20 18:45 UTC, Kobzol commented
LGTM. Btw, I'm leaving for a vacation for a week on Sunday. If you want to get the survey up & running by then, it would be great if we could get the survey PR up soon-ish so that I can prepare the questions and launch the survey :) But I think that your original timeplan already counted with that.

2024-08-20 18:46 UTC, jamesmunns commented
@Kobzol if this gets merged during our meeting (now), I'll have it submitted within an hour :)

btw do you have any thoughts or objections for running this for 4w instead of 2w? Some folks expressed concern that it's currently vacation season, and it might be better to run it a whole month.

2024-08-20 18:47 UTC, adamgreig commented on surveys/2024-08-survey.md
> +This is the first Rust Embedded Working Group community survey. The goal is to gather feedback from users of Rust on Bare Metal or RTOS based embedded devices including microcontrollers.
```suggestion
This is the first Rust Embedded Working Group community survey. The goal is to gather feedback from users of Rust on bare-metal or RTOS based embedded devices including microcontrollers.
```

2024-08-20 18:47 UTC, adamgreig commented on surveys/2024-08-survey.md
> +- School or University projects
```suggestion
- School or university projects
```

2024-08-20 18:47 UTC, adamgreig commented on surveys/2024-08-survey.md
> +- More than 10000 devices per year
```suggestion
- 100 to 1,000 devices per year
- 1,000 to 10,000 devices per year
- More than 10,000 devices per year
```

2024-08-20 18:49 UTC, adamgreig approved these changes

2024-08-20 18:51 UTC, Kobzol commented
> btw do you have any thoughts or objections for running this for 4w instead of 2w? Some folks expressed concern that it's currently vacation season, and it might be better to run it a whole month.

Sounds reasonable, we did something similar with the annual survey last year, because we were only able to get it out just before the December holiday season.

2024-08-20 18:54 UTC, merged